### ISSUE TITLE
[BUG] Proof found, no reward (Windows)

### ISSUE THREAD

**Issue by Threadgodripper** [Equality-Network/equality-blockchain#2]
**Describe the bug**
A clear and concise description of what the bug is. (If what you are experiencing is NOT a bug but instead a support issue, please open a Discussion instead!)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. Linux]
- OS Version/Flavor: [e.g. CentOS 7.2]
- CPU: [e.g. Intel Xeon 8175M]

**Additional context**

**Comment by ghost** [comment]
same boat lot of proof found nothing on wallet

**Comment by 1617176084** [comment]
same boat lot of proof found nothing on wallet

**Comment by reall4uk** [comment]
I have the same problem

**Comment by Numlocket** [comment]
I have same problem.
OS:windows 10
Cpu:intel core i5 10400

**Comment by LimakKAAM** [comment]
Windows app not synced and port open . Why? Where ip peers?

**Comment by YANSIHSU** [comment]
![IMAG1274](https://user-images.githubusercontent.com/86711156/124666017-fa44a800-de9c-11eb-9a4e-aca5477326df.jpg)
proof fpund, no reward. and syncing stopped at height 23054

**Comment by LimakKAAM** [comment]
App working! 
![Screenshot_20210707-043518_Microsoft Remote Desktop](https://user-images.githubusercontent.com/86302894/124691826-c9846300-dedc-11eb-8427-79038aeeba78.jpg)

**Comment by hexter2018** [comment]
Current Blockchain : 34720
