### ISSUE TITLE
[BUG]Unable to synchronize, please give me a node

### ISSUE THREAD

**Issue by 1617176084** [Equality-Network/equality-blockchain#4]
Unable to synchronize, please give me a node

**Comment by hexter2018** [comment]
158.247.192.198
27.254.106.38
27.254.106.36
49.231.200.9
119.76.48.244

**Comment by 1617176084** [comment]
> 158.247.192.198
> 27.254.106.38
> 27.254.106.36
> 49.231.200.9
> 119.76.48.244


What is the port number?

**Comment by hexter2018** [comment]
> > 158.247.192.198
> > 27.254.106.38
> > 27.254.106.36
> > 49.231.200.9
> > 119.76.48.244
> 
> What is the port number?

9888

**Comment by 1617176084** [comment]
> > > 158.247.192.198
> > > 27.254.106.38
> > > 27.254.106.36
> > > 49.231.200.9
> > > 119.76.48.244
> > 
> > 
> > What is the port number?
> 
> 9888

I'm using V1.1.715...This version does not link to these nodes

**Comment by hexter2018** [comment]
> > > > 158.247.192.198
> > > > 27.254.106.38
> > > > 27.254.106.36
> > > > 49.231.200.9
> > > > 119.76.48.244
> > > 
> > > 
> > > What is the port number?
> > 
> > 
> > 9888
> 
> I'm using V1.1.715...This version does not link to these nodes

All node is running

**Comment by nitishmittal** [comment]
Can you provide db file with updatd sync

**Comment by hexter2018** [comment]
> Can you provide db file with updatd sync

https://www.dropbox.com/s/yc405bw5yio0l1b/blockchain_v1_mainnet.sqlite?dl=0

**Comment by Satheeshks3** [comment]
After update Not Syncing.. plz update the node address plz

**Comment by hexter2018** [comment]
> After update Not Syncing.. plz update the node address plz

node1.equalitychain.org:9888
node2.equalitychain.org:9888
node3.equalitychain.org:9888
node4.equalitychain.org:9888
