### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by demusss** [Equality-Network/equality-blockchain#5]
fresh install of 1.1.715
after putting in 24 mnemonics and select safe to skip just have spinning thingy. Tried 4 times

Think the problem maybe due to this in the log

Cannot connect to host introducer.equalitychain.org:9888

**Comment by hexter2018** [comment]
> fresh install of 1.1.715
> after putting in 24 mnemonics and select safe to skip just have spinning thingy. Tried 4 times
> 
> Think the problem maybe due to this in the log
> 
> Cannot connect to host introducer.equalitychain.org:9888

host all ready.
